env:
  browser: true
  es6: true
extends:
  - 'plugin:vue/essential'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaVersion: 2018
  parser: '@typescript-eslint/parser'
  sourceType: module
plugins:
  - vue
  - '@typescript-eslint'
rules:
  eqeqeq: error
  curly: error
  quotes:
    - error
    - single
  indent:
    - error
    - 4
  comma-dangle:
    - error
    - never
  semi:
    - error
    - never
  no-empty: warn
  linebreak-style: error
  no-console: error
  no-unused-vars: error
